version: '3.3'

services:
  career_backend:
    container_name: career_backend
    build: ./backend
    ports:
      - "8000:8000"
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/:/app/

  career_redis:
    container_name: career_redis
    image: redis:alpine
    volumes:
      - "./redis-data:/data"

  career_celery:
    container_name: career_celery
    build: ./backend/
    command: celery -A backend worker -l info
    volumes:
      - ./backend/:/app/
      - ./media/:/media/
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - career_redis

  career_celery_beat:
    container_name: career_celery_beat
    build: ./backend/
    command: celery -A backend beat -l info
    volumes:
      - ./backend/:/app/
      - ./media/:/media/
    restart: always
    env_file:
      - ./app/.env
    depends_on:
      - career_redis