# Generated by Django 4.1 on 2025-04-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, unique=True)),
                ('marka', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('vin', models.CharField(max_length=255)),
                ('not_weight', models.BooleanField(default=False, help_text='Не взвешивать')),
            ],
        ),
    ]
