# Generated by Django 4.1 on 2025-04-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', 'manager'), ('logist', 'logist')], max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('username__isnull', False), ('email__isnull', False), _connector='OR'), name='username or email'),
        ),
    ]
