# Generated by Django 4.2.21 on 2025-06-10 07:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('onec', '0002_alter_price_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('reg_number', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('our_prorerty', models.BooleanField(default=False)),
                ('trailer_reg_number', models.CharField(blank=True, max_length=255, null=True)),
                ('trailer_brand', models.CharField(blank=True, max_length=255, null=True)),
                ('not_weight', models.BooleanField(default=False, help_text='Не взвешивать')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='car')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('inn', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('drivers_license_series', models.CharField(blank=True, max_length=255, null=True)),
                ('drivers_license_number', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='driver')),
                ('telegram_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='do_not_display_volume',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='specification',
            name='nomenclatures',
            field=models.ManyToManyField(blank=True, to='onec.nomenclature'),
        ),
        migrations.AddField(
            model_name='specification',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='onec.organization'),
        ),
    ]
