# Generated by Django 4.2.20 on 2025-06-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onec', '0003_car_driver_organization_do_not_display_volume_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('nomenclature', 'specification', 'date')},
        ),
    ]
