# Generated by Django 4.2.21 on 2025-11-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onec', '0004_alter_price_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
    ]
