# Generated by Django 4.2.21 on 2025-11-28 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onec', '0005_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='onec.sender'),
            preserve_default=False,
        ),
    ]
