# Generated by Django 4.2.21 on 2026-06-16 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onec', '0007_driver_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='onec.sender'),
        ),
    ]
