# Generated by Django 4.1 on 2025-04-01 15:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0002_car_created_at_car_image'),
        ('onec', '0001_initial'),
        ('driver', '0002_driver_created_at_driver_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('prepayment', 'Предоплата'), ('deferment_payment', 'Отсрочка платежа'), ('limit', 'Лимит')], max_length=255)),
                ('status', models.CharField(choices=[('created', 'Принято'), ('process', 'В обработке'), ('done', 'Успешно'), ('canceled', 'Отклонено')], default='created', max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onec.organization')),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onec.specification')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('per_price', models.FloatField()),
                ('price', models.FloatField()),
                ('additive', models.FloatField(help_text='Добавка')),
                ('order', models.FloatField(help_text='Заказ')),
                ('fact', models.FloatField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car.car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='driver.driver')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onec.nomenclature')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceNomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.invoice')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='onec.nomenclature')),
            ],
            options={
                'unique_together': {('nomenclature', 'invoice')},
            },
        ),
    ]
