# Generated by Django 4.1 on 2025-04-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_created_at_invoice_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='additive',
            field=models.FloatField(blank=True, help_text='Добавка', null=True),
        ),
    ]
