# Generated by Django 4.1 on 2025-05-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_order_additive'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_comments',
            field=models.JSONField(default=list),
        ),
    ]
