# Generated by Django 4.1 on 2025-05-21 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_comment_order_comment_order_driver_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='driver_comments',
        ),
        migrations.CreateModel(
            name='DriverComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('loading', 'Загрузка'), ('ok', 'Успешно'), ('error', 'Ошибка')], default='loading', max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.order')),
            ],
        ),
    ]
