# Generated by Django 4.2.21 on 2025-06-10 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_remove_order_driver_comments_drivercomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='car',
        ),
        migrations.RemoveField(
            model_name='order',
            name='driver',
        ),
    ]
