# Generated by Django 4.2.21 on 2025-06-10 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onec', '0003_car_driver_organization_do_not_display_volume_and_more'),
        ('invoice', '0006_remove_order_car_remove_order_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='onec.car'),
        ),
        migrations.AddField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='onec.driver'),
        ),
    ]
